### ISSUE TITLE
How to configure the UEFI boot options?

### ISSUE THREAD

**Issue by rgl** [tinkerbell/tinkerbell-docs#126]
To properly install an OS in a UEFI machine we need to reset the existing UEFI boot options and configure UEFI to boot the new OS.

In a regular debian root shell, we can do this as:

```bash
# delete all boot options (the BootXXXX UEFI variables).
efibootmgr \
  | perl -n -e '/^Boot([0-9A-F]{4})/ && print "$1\n"' \
  | xargs -I% efibootmgr --quiet --delete-bootnum --bootnum %
efibootmgr --quiet --delete-bootorder
# install the current OS boot option.
grub-install
```

While trying to transpose this to tinkerbell, I've failed to use the `cexec` action in this non-working workflow:

```yaml
version: "0.1"
name: debian
global_timeout: 1800
tasks:
  - name: debian-install
    worker: '{{.device_1}}'
    volumes:
      - /dev:/dev
      - /sys/firmware/efi/efivars:/sys/firmware/efi/efivars
      - /worker:/worker
    actions:
      - name: install
        image: image2disk:v1.0.0
        environment:
          IMG_URL: '{{.img_url}}'
          COMPRESSED: true
          DEST_DISK: '{{.boot_device}}'
      - name: configure-uefi
        image: cexec:v1.0.0
        environment:
          BLOCK_DEVICE: '{{.boot_device}}3'
          FS_TYPE: ext4
          CHROOT: y
          DEFAULT_INTERPRETER: /bin/bash -euxo pipefail -c
          CMD_LINE: |
            # delete all the boot options (the firmware will recover them at the next boot).
            # you can also explicitly install it.
            mount
            efibootmgr
            efibootmgr \
              | perl -n -e '/^Boot([0-9A-F]{4})/ && print "$1\n"' \
              | xargs -I% efibootmgr --quiet --delete-bootnum --bootnum %
            efibootmgr --quiet --delete-bootorder
            grub-install --root-directory=/boot {{.boot_device}}
            efibootmgr
      - name: reboot
        image: reboot
```

This fails to execute the `configure-uefi` action because the `/sys/firmware/efi/efivars` is not mounted in the `cexec` created chroot:

![screenshot](https://user-images.githubusercontent.com/43356/133405081-e18e5c18-d6ff-4ed8-a653-56ba05e1cce3.png)

So, how can this be done?

Should a new action for the `efibootmgr` exist? and only use `cexec` for running `grub-install`?

**Comment by rgl** [comment]
FWIW, I've created a new `reset-uefi-boot` action that deletes all the `BootXXX` UEFI variables with `efibootmgr --quiet --delete-bootnum --bootnum` and is executed in a workflow like:

```yaml
version: "0.1"
name: debian
global_timeout: 1800
tasks:
  - name: debian-install
    worker: '{{.device_1}}'
    volumes:
      - /dev:/dev
      - /sys/firmware/efi/efivars:/sys/firmware/efi/efivars
      - /worker:/worker
    actions:
      - name: install
        image: image2disk:v1.0.0
        environment:
          IMG_URL: '{{.img_url}}'
          COMPRESSED: true
          DEST_DISK: '{{.boot_device}}'
      - name: reset-uefi-boot
        image: reset-uefi-boot
      - name: reboot
        image: reboot
```
